import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import type { UserOptions } from 'jspdf-autotable';
import type { Profile, Medication, MedicationChange, SymptomCheckin, LabResult } from '../types/database';
import { APP_NAME } from '../lib/constants';
import { formatChartDateLong } from './chartHelpers';
import { formatFrequency } from './medicationHelpers';
import { MRS_CORE_SYMPTOMS } from '../data/symptoms';
import { getMRSSeverityTier, getMRSSeverityLabel } from './checkinHelpers';
import { getBiomarkerByKey } from '../data/labRanges';
import { getBiomarkerValue, getValueStatus, BIOMARKER_KEYS } from './labHelpers';
import type { DateRange } from '../stores/dashboardStore';

const DISCLAIMER =
  'This report is for informational purposes only and does not constitute medical advice.';

function addFooter(doc: jsPDF, pageNum: number) {
  const pageHeight = doc.internal.pageSize.height;
  doc.setFontSize(8);
  doc.setTextColor(120, 120, 120);
  doc.text(
    `Generated by ${APP_NAME} on ${formatChartDateLong(new Date().toISOString().split('T')[0])}. ${DISCLAIMER}`,
    14,
    pageHeight - 10,
    { maxWidth: 180 },
  );
  doc.text(`Page ${pageNum}`, 190, pageHeight - 10, { align: 'right' });
}

function getTrendLabel(current: number, prior: number | undefined): string {
  if (prior === undefined) return 'Insufficient data';
  const diff = current - prior;
  if (diff === 0) return 'Stable';
  return diff < 0 ? 'Improving' : 'Worsening';
}

export async function generateProviderReport(data: {
  profile: Profile;
  medications: Medication[];
  medicationChanges: MedicationChange[];
  checkins: SymptomCheckin[];
  labResults: LabResult[];
  dateRange: DateRange;
}): Promise<Blob> {
  const doc = new jsPDF();
  let pageNum = 1;

  const sortedCheckins = [...data.checkins]
    .filter((c) => c.checkin_date >= data.dateRange.start && c.checkin_date <= data.dateRange.end)
    .sort((a, b) => a.checkin_date.localeCompare(b.checkin_date));

  const latest = sortedCheckins[sortedCheckins.length - 1];
  const earliest = sortedCheckins[0];
  const thirtyDaysAgo = new Date();
  thirtyDaysAgo.setDate(thirtyDaysAgo.getDate() - 30);
  const thirtyStr = thirtyDaysAgo.toISOString().split('T')[0];
  const prior =
    sortedCheckins.filter((c) => c.checkin_date <= thirtyStr).slice(-1)[0] ??
    earliest;

  // Page 1: Summary
  doc.setFontSize(18);
  doc.setTextColor(40, 40, 40);
  doc.text(`${APP_NAME} — Provider Report`, 14, 22);
  doc.setFontSize(10);
  doc.text(`Patient: ${data.profile.display_name ?? 'Patient'}`, 14, 34);
  doc.text(
    `Period: ${formatChartDateLong(data.dateRange.start)} – ${formatChartDateLong(data.dateRange.end)}`,
    14,
    41,
  );
  doc.text(`Generated: ${formatChartDateLong(new Date().toISOString().split('T')[0])}`, 14, 48);

  if (latest) {
    doc.text(
      `Current MRS: ${latest.total_score}/64 (${getMRSSeverityLabel(getMRSSeverityTier(latest.total_score))})`,
      14,
      58,
    );
    doc.text(
      `Subscales — Vasomotor: ${latest.somatic_score}/12 · Psychological: ${latest.psychological_score}/20 · Urogenital: ${latest.urogenital_score}/12`,
      14,
      65,
    );
    if (latest.overall_wellbeing != null) {
      doc.text(`Wellbeing: ${latest.overall_wellbeing}/10`, 14, 72);
    }
    doc.text(
      `30-day trend: ${getTrendLabel(latest.total_score, prior?.total_score)}`,
      14,
      79,
    );
  }

  const activeMeds = data.medications.filter((m) => m.is_active);
  autoTable(doc, {
    startY: 88,
    head: [['Medication', 'Dose', 'Frequency', 'Started']],
    body: activeMeds.map((m) => [
      m.medication_name,
      `${m.dose_amount} ${m.dose_unit}`,
      formatFrequency(m.frequency),
      formatChartDateLong(m.start_date),
    ]),
    theme: 'grid',
    headStyles: { fillColor: [190, 115, 154] },
    styles: { fontSize: 9 },
  });

  addFooter(doc, pageNum);

  // Page 2: Symptom Trends
  doc.addPage();
  pageNum++;
  doc.setFontSize(14);
  doc.text('Symptom Trends', 14, 22);

  if (earliest && latest) {
    doc.setFontSize(10);
    doc.text(`Overall MRS: ${earliest.total_score} → ${latest.total_score}`, 14, 32);
    if (earliest.overall_wellbeing != null && latest.overall_wellbeing != null) {
      doc.text(`Wellbeing: ${earliest.overall_wellbeing} → ${latest.overall_wellbeing}`, 14, 39);
    }
  }

  const symptomRows = MRS_CORE_SYMPTOMS.map((symptom) => {
    const key = symptom.key as keyof SymptomCheckin;
    const startScore = earliest ? (earliest[key] as number | null) : null;
    const endScore = latest ? (latest[key] as number | null) : null;
    let trend = '—';
    if (startScore !== null && endScore !== null) {
      if (endScore < startScore) trend = 'Improved';
      else if (endScore > startScore) trend = 'Worsened';
      else trend = 'Stable';
    }
    return [
      symptom.label,
      startScore ?? '—',
      endScore ?? '—',
      trend,
    ];
  });

  autoTable(doc, {
    startY: 48,
    head: [['Symptom', 'Start', 'End', 'Trend']],
    body: symptomRows,
    theme: 'striped',
    headStyles: { fillColor: [190, 115, 154] },
    styles: { fontSize: 8 },
  });

  addFooter(doc, pageNum);

  // Page 3: Medication History
  doc.addPage();
  pageNum++;
  doc.setFontSize(14);
  doc.text('Medication History', 14, 22);

  const medRows = data.medications
    .filter(
      (m) =>
        m.start_date <= data.dateRange.end &&
        (m.end_date ?? '9999-12-31') >= data.dateRange.start,
    )
    .map((m) => [
      m.medication_name,
      `${m.dose_amount} ${m.dose_unit}`,
      m.is_active ? 'Active' : 'Stopped',
      formatChartDateLong(m.start_date),
      m.end_date ? formatChartDateLong(m.end_date) : '—',
    ]);

  autoTable(doc, {
    startY: 30,
    head: [['Medication', 'Dose', 'Status', 'Started', 'Stopped']],
    body: medRows,
    theme: 'grid',
    headStyles: { fillColor: [190, 115, 154] },
    styles: { fontSize: 8 },
  });

  const changeRows = data.medicationChanges
    .filter((c) => c.change_date >= data.dateRange.start && c.change_date <= data.dateRange.end)
    .sort((a, b) => a.change_date.localeCompare(b.change_date))
    .map((c) => {
      const med = data.medications.find((m) => m.id === c.medication_id);
      return [
        formatChartDateLong(c.change_date),
        med?.medication_name ?? '—',
        c.change_type.replace(/_/g, ' '),
        c.previous_dose != null ? String(c.previous_dose) : '—',
        c.new_dose != null ? String(c.new_dose) : '—',
        c.notes ?? '',
      ];
    });

  if (changeRows.length > 0) {
    autoTable(doc, {
      startY: (doc.lastAutoTable?.finalY ?? 30) + 10,
      head: [['Date', 'Medication', 'Change', 'Prev Dose', 'New Dose', 'Notes']],
      body: changeRows,
      theme: 'striped',
      headStyles: { fillColor: [190, 115, 154] },
      styles: { fontSize: 8 },
    });
  }

  addFooter(doc, pageNum);

  // Page 4: Labs
  const sortedLabs = [...data.labResults]
    .filter((l) => l.draw_date >= data.dateRange.start && l.draw_date <= data.dateRange.end)
    .sort((a, b) => b.draw_date.localeCompare(a.draw_date));

  if (sortedLabs.length > 0) {
    doc.addPage();
    pageNum++;
    doc.setFontSize(14);
    doc.text('Lab Results', 14, 22);

    const latestLab = sortedLabs[0];
    const priorLab = sortedLabs[1];
    const filledKeys = BIOMARKER_KEYS.filter(
      (key) => getBiomarkerValue(latestLab, key) !== null,
    );

    const labRows: string[][] = [];
    for (const key of filledKeys) {
      const biomarker = getBiomarkerByKey(key);
      if (!biomarker) continue;
      const value = getBiomarkerValue(latestLab, key)!;
      const status = getValueStatus(value, biomarker);
      const priorVal = priorLab ? getBiomarkerValue(priorLab, key) : null;
      let trend = '—';
      if (priorVal !== null) {
        trend = value > priorVal ? '↑' : value < priorVal ? '↓' : '→';
      }
      const range = biomarker.optimalRange
        ? `${biomarker.optimalRange.min}–${biomarker.optimalRange.max}`
        : biomarker.conventionalRange
          ? `${biomarker.conventionalRange.min}–${biomarker.conventionalRange.max}`
          : '—';
      labRows.push([
        biomarker.label,
        `${value} ${biomarker.unit}`,
        range,
        status.replace(/_/g, ' '),
        trend,
      ]);
    }

    doc.setFontSize(10);
    doc.text(`Most recent draw: ${formatChartDateLong(latestLab.draw_date)}`, 14, 32);

    autoTable(doc, {
      startY: 38,
      head: [['Biomarker', 'Value', 'Reference', 'Status', 'Trend']],
      body: labRows,
      theme: 'grid',
      headStyles: { fillColor: [190, 115, 154] },
      styles: { fontSize: 8 },
      didParseCell: (hookData) => {
        if (hookData.section === 'body' && hookData.column.index === 3) {
          const status = hookData.cell.raw as string;
          if (status.includes('out of range')) {
            hookData.cell.styles.textColor = [181, 79, 79];
            hookData.cell.styles.fontStyle = 'bold';
          }
        }
      },
    } satisfies UserOptions);

    addFooter(doc, pageNum);
  }

  return doc.output('blob');
}
