import type jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { APP_NAME } from '../../../lib/constants';
import type { Profile, Medication } from '../../../types/database';
import type { DateRange } from '../../../stores/dashboardStore';
import type { PdfPageContext } from '../pdfTheme';
import { PDF_COLORS, drawSectionHeader } from '../pdfTheme';
import { formatChartDateLong } from '../../chartHelpers';
import { formatMedicationDoseShort } from '../../medicationHelpers';
import {
  computeAge,
  formatStagingBasis,
  formatStrawStageDisplay,
  computeAdherence,
  formatReportDateRange,
  formatMenopauseCauseNote,
} from '../reportData';

const DISCLAIMER =
  'This report was generated by PredictHer, a symptom tracking application. It is intended to support clinical conversations, not replace professional medical judgment.';

export function renderPatientSummaryPage(
  ctx: PdfPageContext,
  profile: Profile,
  medications: Medication[],
  checkinDates: string[],
  dateRange: DateRange,
): number {
  const { doc } = ctx;
  let y = 18;

  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...PDF_COLORS.accent);
  doc.text(APP_NAME, 14, y);

  y += 10;
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...PDF_COLORS.text);
  doc.text('Patient Health Report', 14, y);

  y += 10;
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...PDF_COLORS.textMuted);
  doc.text(formatReportDateRange(dateRange.start, dateRange.end), 14, y);

  y += 8;
  doc.setFontSize(8);
  const disclaimerLines = doc.splitTextToSize(DISCLAIMER, 180);
  doc.text(disclaimerLines, 14, y);
  y += disclaimerLines.length * 3.5 + 8;

  y = drawSectionHeader(doc, 'Patient Information', y);

  const age = computeAge(profile.date_of_birth);
  const adherence = computeAdherence(
    checkinDates,
    profile.checkin_frequency,
    dateRange.start,
    dateRange.end,
  );

  const infoRows: [string, string][] = [
    ['Name', profile.display_name ?? 'Patient'],
    ['Age', age !== null ? String(age) : 'Not provided'],
    ['STRAW+10 Stage', formatStrawStageDisplay(profile)],
    ['Staging basis', formatStagingBasis(profile)],
  ];

  const causeNote = formatMenopauseCauseNote(profile);
  if (causeNote) {
    infoRows.push(['', causeNote]);
  }

  infoRows.push([
    'Check-in frequency & adherence',
    `${adherence.label}, ${adherence.percent}% adherence over reporting period`,
  ]);

  doc.setFontSize(9);
  for (const [label, value] of infoRows) {
    if (label) {
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(...PDF_COLORS.header);
      doc.text(`${label}:`, 14, y);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(...PDF_COLORS.text);
      const lines = doc.splitTextToSize(value, 120);
      doc.text(lines, 60, y);
      y += Math.max(lines.length * 4.5, 6);
    } else {
      doc.setTextColor(...PDF_COLORS.textMuted);
      doc.text(value, 60, y);
      y += 5;
    }
  }

  y += 4;
  y = drawSectionHeader(doc, 'Current Medications', y);

  const activeMeds = medications.filter((m) => m.is_active);

  if (activeMeds.length === 0) {
    doc.setFontSize(9);
    doc.setTextColor(...PDF_COLORS.textMuted);
    doc.text('No active medications recorded.', 14, y + 4);
    return y + 12;
  }

  autoTable(doc, {
    startY: y,
    head: [['Medication', 'Dose & delivery', 'Start date']],
    body: activeMeds.map((m) => [
      m.medication_name,
      `${formatMedicationDoseShort(m)} · ${m.delivery_method.replace(/_/g, ' ')}`,
      formatChartDateLong(m.start_date),
    ]),
    theme: 'grid',
    headStyles: { fillColor: PDF_COLORS.tableHead, textColor: [255, 255, 255], fontSize: 8 },
    styles: { fontSize: 8, textColor: PDF_COLORS.text },
    alternateRowStyles: { fillColor: PDF_COLORS.tableStripe },
    margin: { left: 14, right: 14 },
  });

  return (doc as jsPDF & { lastAutoTable?: { finalY: number } }).lastAutoTable?.finalY ?? y + 20;
}
